# Generated by Django 4.2.7 on 2023-12-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alugueis',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('servicos', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='static/img/')),
            ],
            options={
                'db_table': 'alugueis',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('servicos', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='static/img/')),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('servicos', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='static/img/')),
            ],
            options={
                'db_table': 'ofertas',
            },
        ),
        migrations.CreateModel(
            name='Pacotes',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('expedicao', models.CharField(max_length=50)),
                ('servicos', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='static/img/')),
            ],
            options={
                'db_table': 'pacotes',
            },
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('servicos', models.CharField(max_length=255)),
                ('destinos', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'passagem',
            },
        ),
        migrations.CreateModel(
            name='Seguros',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'seguros',
            },
        ),
    ]
